version: '2'

services:
  database:
    image: mongo:6
    restart: always
    volumes:
      - ./init-mongodb:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: "gsbv"
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "12345"

  backend:
    depends_on:
      - database
    build: .
    restart: always
    ports:
      - "127.0.0.1:9909:3000"
    environment:
      DB_URL: "mongodb://gsbv:gsbv@database/gsbv"
      PORT: "3000"
      JWT_TOKEN: "OpfrhfMj1wC6FrDH0Zvwe/o6lQyDSqgcaapThuE="
